title: joaomarcuslf
email: jmarcusfernandes@gmail.com
description: > 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "http://joaomarcuslf.github.io"
twitter_username: joaomarcuslf
github_username:  joaomarcuslf
encoding: utf-8
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
host: 0.0.0.0

markdown: kramdown
