title: joaomarcuslf
email: jmarcusfernandes@gmail.com
description: > 
  João Marcus Fernandes, Coffee lover, front-end developer and UX/UI designer.
  I like to code as much as I like coffee.
baseurl: "/"
url: "http://joaomarcuslf.github.io"
twitter_username: joaomarcuslf
github_username:  joaomarcuslf
encoding: utf-8
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
host: 0.0.0.0

production_url : http://joaomarcuslf.github.io
gems: ["jekyll-sitemap", "webrick"]

exclude: [
  "node_modules",
  "bower_components",
  ".sass-cache"
]

markdown: kramdown
